version: "3.5"
services:
  rabbit:
    image: rabbitmq:3.8.5-management
    ports:
      - '15673:15672' # in case user has rabbitMQ installed on host
    environment:
      - RABBITMQ_DEFAULT_USER=axiome3
      - RABBITMQ_DEFAULT_PASS=neufeld
      - RABBITMQ_DEFAULT_VHOST=axiome3_host

  # flower:
  #   build:
  #     context: ./flower
  #     dockerfile: Dockerfile
  #   # note: originally the command was: /flower/wait-for-it.sh rabbit:5672 -- celery --broker=amqp://axiome3:neufeld@rabbit:5672/axiome3_host flower --broker_api=http://axiome3:neufeld@rabbit:15672/api/axiome3_host --port=5555
  #   # However, due to flower using an outdated jQuery, it causes IST issues and has been disabled
  #   # If one day jQuery is updated for flower, we can start using it again
  #   command: "/flower/wait-for-it.sh rabbit:5672 -- celery --broker=amqp://axiome3:neufeld@rabbit:5672/axiome3_host"
  #   ports:
  #     - 5555:5555
  #   restart: on-failure
  #   volumes:
  #     - ./flower:/flower

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      args:
        #- QIIME2_RELEASE=2022.2
        - QIIME2_RELEASE=2020.6
        - CLASSIFIER_GDRIVE_ID=12jug9XZcbUefevtTnENGudjGqaAL0LCo
    command: ["python", "prod_server.py", '--py-autoreload', '1']
    volumes:
      - ../../backend:/backend
      - ../../pipeline:/pipeline
      - /:/hostfs:ro # Assumes host root is '/'
      - /Analysis/AXIOME3/output:/output # Stores all the output to this directory
      - ../../log:/log # For logging
      - input:/input # Named volume
    ports:
      - '5000'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=AXIOME3_app/app
      - PYTHONPATH=/pipeline # Add AXIOME3 pipeline to PYTHONPATH
      - LUIGI_CONFIG_PATH=/pipeline/configuration/luigi.cfg
      - GMAIL_SENDER=axiome333@gmail.com
      - RUN_ENV=8080
    restart: on-failure

  pipeline_worker:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      args:
        #- QIIME2_RELEASE=2022.2
        - QIIME2_RELEASE=2020.6
        - CLASSIFIER_GDRIVE_ID=12jug9XZcbUefevtTnENGudjGqaAL0LCo
    command: "celery -A AXIOME3_app.celery_app:app worker --concurrency=1 -n worker1@%h -Q pipeline --loglevel=INFO"
    volumes:
      - /:/hostfs:ro # Assumes host root is '/'
      - ../../backend:/backend
      - ../../pipeline:/pipeline
      - /Analysis/AXIOME3/output:/output # Stores all the output to this directory
      - ../../log:/log # For logging
      - input:/input # Named volume
    environment:
      - PYTHONPATH=/pipeline # Add AXIOME3 pipeline to PYTHONPATH
      - LUIGI_CONFIG_PATH=/pipeline/configuration/luigi.cfg
      - GMAIL_SENDER=axiome333@gmail.com
      - RUN_ENV=8080
    restart: on-failure

  extension_worker:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      args:
        #- QIIME2_RELEASE=2022.2
        - QIIME2_RELEASE=2020.6
        - CLASSIFIER_GDRIVE_ID=12jug9XZcbUefevtTnENGudjGqaAL0LCo
    command: "celery -A AXIOME3_app.celery_app:app worker --concurrency=1 -n worker2@%h -Q extension --loglevel=INFO"
    volumes:
      - /:/hostfs:ro # Assumes host root is '/'
      - ../../backend:/backend
      - ../../pipeline:/pipeline
      - /Analysis/AXIOME3/output:/output # Stores all the output to this directory
      - ../../log:/log # For logging
      - input:/input # Named volume
    environment:
      - PYTHONPATH=/pipeline # Add AXIOME3 pipeline to PYTHONPATH
      - RUN_ENV=8080
    restart: on-failure

  app:
    build:
      context: ../../
      dockerfile: ./docker_files/mellea/8080.Dockerfile
      # args:
      #   - REACT_APP_QIIME2_RELEASE=2020.6
      #   - REACT_APP_SILVA_VERSION=138
      #   - REACT_APP_RUN_ENV=8080
      #   - REACT_APP_OUTPUT_DIR_PATH=/hostfs/Analysis/AXIOME3/output
    volumes:
      - ../../nginx/prod/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    depends_on:
      - backend
    environment:
      - PORT=8080
      - REACT_APP_QIIME2_RELEASE=2020.6
      - REACT_APP_SILVA_VERSION=138
      - REACT_APP_RUN_ENV=8080
      - REACT_APP_OUTPUT_DIR_PATH=/hostfs/Analysis/AXIOME3/output # will still run without this since it exists in Dockerfile, but leaving it in just in case
    command: "nginx -g 'daemon off;'"

volumes:
  input:
  node_module: